require "rspec/core/rake_task"
RSpec::Core::RakeTask.new(:spec).ruby_opts = "-I ."

# https://docs.rubocop.org/en/latest/integration_with_other_tools/#rake-integration
require "rubocop/rake_task"
RuboCop::RakeTask.new(:rubocop) do |task|
  task.fail_on_error = false
end

task default: %i[rubocop spec]
